services:
    local.api.forecast.com.br:
        build:
            context: '.docker/php-${PHP_VERSION:-8.2}'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-${PHP_VERSION:-8.2}/app'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
            - '.docker/php-${PHP_VERSION:-8.2}/php.ini:/etc/php/${PHP_VERSION:-8.2}/cli/conf.d/99-sail.ini'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - sail
        depends_on:
            - pgsql
            - redis
    nginx:
        image: 'nginx:alpine'
        depends_on:
            - local.api.forecast.com.br
        volumes:
            - '${DOCKER_APP_DIR:-./src}:/var/app'
            - '${DOCKER_ADM_DIR:-./src}:/var/adm'
            - '.docker/nginx/vhosts.conf:/etc/nginx/conf.d/default.conf'
            - '.docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - sail
    pgsql:
        image: 'postgres:13'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sailpgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sailpgsql:
        driver: local
    sailredis:
        driver: local
